- hosts: all
  become: yes
  tasks:

    - name: Копирование JAR на сервер
      copy:
        src: ../target/jenkins_sonar-1.0-SNAPSHOT.jar
        dest: application.jar

    - name: Запуск JAR
      shell: java -jar application.jar